name: "Create Jira Story"
description: "A GitHub Action to create a Jira issue"
inputs:
  jira_base_url:
    description: "The base URL of your Jira instance"
    required: true
  jira_user_email:
    description: "The email address of the Jira user"
    required: true
  jira_api_token:
    description: "The API token for Jira authentication"
    required: true
  jira_project_key:
    description: "The Jira project key where the issue will be created"
    required: true
  issue_summary:
    description: "Summary of the issue"
    required: true
  issue_description:
    description: "Description of the issue or path to a file containing the description"
    required: true
  log_file_path:
    description: "Path to the log file containing the description"
    required: false
runs:
  using: "node20"
  main: "index.js"
