name: "Create Jira Story"
description: "A GitHub Action to create or update a Jira issue"
inputs:
  jira_base_url:
    description: "The base URL of your Jira instance"
    required: true
  jira_user_email:
    description: "The email address of the Jira user"
    required: true
  jira_api_token:
    description: "The API token for Jira authentication"
    required: true
  jira_project_key:
    description: "The Jira project key where the issue will be created"
    required: true
  issue_summary:
    description: "Summary of the issue"
    required: true
  issue_description:
    description: "Description of the issue"
    required: true
  board_id:
    description: "The ID of the Jira board"
    required: true
  sprint_name:
    description: "The name of the sprint to add the issue to"
    required: true
  retry_count:
    description: "The number of times to retry the request"
    required: false
runs:
  using: "node20"
  main: "index.js"
